name: Rails Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.7.2

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      # Use postgres for the host here because we have specified a container for the job.
      # If we were running the job on the VM this would be localhost
      DATABASE_URL: postgres://postgres:@postgres:5432/test
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install PostgreSQL 11 client
      run: |
        apt-get -yqq install libpq-dev

    - name: Install Yarn
      run: |
        npm install yarn -g

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Build App
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        yarn install
        bin/rails db:setup
        bin/rails webpacker:compile

    - name: Run Tests
      run: bundle exec rails test
